routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});

// Requests
Route::group(
    ['middleware' => 'hotel.admin'],
    function () {

        // Main
        Route::get('/', 'MainController@index')->name('main');

        // Orders
        Route::resources(['orders' => 'Hotel\OrdersController'], ['as' => 'hotel']);
        Route::get('/orders/restore/{id}', 'Hotel\OrdersController@restore')->name('hotel.orders.restore');

        // Rooms
        Route::resources(['rooms' => 'Hotel\RoomsController'], ['as' => 'hotel']);
        Route::get('/rooms/restore/{id}', 'Hotel\RoomsController@restore')->name('hotel.rooms.restore');

        // Users
        Route::resources(['users' => 'Hotel\UsersController'], ['as' => 'hotel']);
        Route::get('/search-user', 'Hotel\UsersController@searchUser')->name('hotel.users.searchUser');

        // Guests
        Route::resources(['guests' => 'Hotel\GuestsController'], ['as' => 'hotel']);
        Route::get('/guests/restore/{id}', 'Hotel\GuestsController@restore')->name('hotel.guests.restore');

        // Services
        Route::resources(['services' => 'Hotel\ServicesController'], ['as' => 'hotel']);
        Route::post('/services/update/{id}', 'Hotel\ServicesController@update')->name('hotel.services.update');
        Route::get('/services/restore/{id}', 'Hotel\ServicesController@restore')->name('hotel.services.restore');
        Route::post('/services/image-uploader', 'Hotel\ServicesController@imageUploader')
            ->name('hotel.services.imageUploader');
        Route::post('/services/image-delete', 'Hotel\ServicesController@destroyImage')
            ->name('hotel.services.destroyImage');
        Route::get('/services/archive/{id}/{value}', 'Hotel\ServicesController@archive')
            ->name('hotel.services.archive');

        // Offers
        Route::resources(['offers' => 'Hotel\OffersController'], ['as' => 'hotel']);
        Route::post('/offers/update/{id}', 'Hotel\OffersController@update')->name('hotel.offers.update');
        Route::get('/offers/archive/{id}/{value}', 'Hotel\OffersController@archive')->name('hotel.offers.archive');
        Route::post('/offers/uploader/image-uploader', 'Hotel\OffersController@imageUploader')
            ->name('hotel.offers.imageUploader');
        Route::post('/offers/uploader/image-delete', 'Hotel\OffersController@destroyImage')
            ->name('hotel.offers.destroyImage');

        // News
        Route::resources(['news' => 'Hotel\NewsController'], ['as' => 'hotel']);
        Route::get('/news/archive/{id}/{value}', 'Hotel\NewsController@archive')->name('hotel.news.archive');

        // Articles
        Route::resources(['articles' => 'Hotel\ArticlesController'], ['as' => 'hotel']);
        Route::get('/articles/archive/{id}/{value}', 'Hotel\ArticlesController@archive')
            ->name('hotel.articles.archive');
        Route::get('/hotel/contacts', 'Hotel\ArticlesController@contacts')->name('hotel.contacts');
        Route::patch('/hotel/contacts', 'Hotel\ArticlesController@contactsUpdate')->name('hotel.contacts.update');

        // Settings
        Route::group(['prefix' => 'settings'], function () {
            Route::get('/', 'Hotel\SettingsController@index')->name('hotel.settings.index');
            Route::put('/', 'Hotel\SettingsController@update')->name('hotel.settings.update');
            Route::get('/languages', 'Hotel\SettingsController@languages')->name('hotel.settings.languages');
            Route::get('/currencies', 'Hotel\SettingsController@currencies')->name('hotel.settings.currencies');
        });

        Route::get('/translation', 'MainController@translation')->name('translation');

        // Profile
        Route::group(['prefix' => 'profile'], function () {
            Route::get('/settings', 'User\Profile\SettingsController@index')->name('profile.settings');
            Route::patch('/settings', 'User\Profile\SettingsController@update')->name('profile.settings.update');
        });

        // Users
        Route::resources(['crm-users' => 'User\UsersController'], ['as' => 'hotel']);
		Route::get('/crm-users/block/{id}', 'User\UsersController@blocked')
			->name('hotel.users.block');
    }
);

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Notifications\Notifiable;

/**
 * Class User
 *
 * @package App\Models
 * @method static create(array $array)
 * @method static firstOrCreate(array $array, array $array1)
 * @method static find($id)
 * @method static whereId($id)
 * @method static hotelUsers()
 * @property $hotel_id
 * @property $hotel_admin
 */
class User extends \TCG\Voyager\Models\User
{
    use Notifiable;

    /**
     * @var string[]
     */
    protected $fillable = [
        'lang_id',
        'hotel_id',
        'role_id',
        'crm_role_id',
        'hotel_main',
        'crm',
        'name',
        'email',
        'phone',
        'password',
		'blocked_at',
    ];

    /**
     * @var string[]
     */
    protected $dates = [
        'blocked_at',
        'created_at',
        'updated_at',
    ];

    /**
     * @var string[]
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * @var string[]
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * Type
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     * @author ansotov
     */
    public function language(): BelongsTo
    {
        return $this->belongsTo('App\Models\Language', 'lang_id', 'id');
    }

    /**
     * Hotel
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     * @author ansotov
     */
    public function hotel(): BelongsTo
    {
        return $this->belongsTo('App\Models\Hotels\Hotel', 'hotel_id', 'id');
    }

	/**
	 * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
	 */
    public function crmRole(): BelongsTo
    {
        return $this->belongsTo('App\Models\Permissions\CrmRole', 'crm_role_id', 'id');
    }

    /**
     * Languages
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function languages(): HasMany
    {
        return $this->hasMany(
            'App\Models\Hotels\HotelLanguage',
            'hotel_id',
            'hotel_id'
        )
            ->orderBy('order');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function services(): HasMany
    {
        return $this->hasMany('App\Models\Hotels\HotelService', 'hotel_id', 'hotel_id');
    }

    /**
     * @param \Illuminate\Database\Eloquent\Builder $query
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeHotelUsers(Builder $query): Builder
    {
        return $query->where(
            [
                'hotel_id' => auth()->user()->hotel_id,
                'crm' => true,
            ]
        );
    }
}

app/Http/Controllers/Hotel/UsersController.php
<?php

namespace App\Http\Controllers\Hotel;

use App\Http\Controllers\Controller;
use App\Models\Hotels\HotelUser;
use App\Models\User;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;

/**
 * Class UsersController
 *
 * @package App\Http\Controllers\Hotel
 */
class UsersController extends Controller
{
	/**
	 * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
	 */
	public function create(): View
	{
		return view('hotel.users.ajax.addUser');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param \Illuminate\Http\Request $request
	 *
	 * @return bool
	 */
	public function store(Request $request): bool
	{
		$request->validate([
			'name'    => 'required',
			'phone'   => 'required',
			'email'   => 'required',
			'lang_id' => 'required',
		]);

		$request->name  = trim($request->name);
		$request->phone = str_replace(' ', '', $request->phone);
		$request->email = trim($request->email);

		$user = User::firstOrCreate(
			[
				'phone' => $request->phone
			],
			[
				'lang_id'  => $request->lang_id,
				'role_id'  => $this->role('user')->id,
				'name'     => $request->name,
				'phone'    => $request->phone,
				'email'    => $request->email,
				'password' => str_random(8),
			]
		);


		$request->validate([
			'phone' => 'required|unique:hotel_users,phone,hotel_id',
			'email' => 'required|unique:hotel_users,email,hotel_id',
		]);

		HotelUser::firstOrCreate(
			[
				'phone' => $request->phone
			],
			[
				'user_id'       => $user->id,
				'hotel_id'      => auth()->user()->hotel_id,
				'name'          => $request->name,
				'phone'         => $request->phone,
				'email'         => $request->email,
				'personal_data' => $request->personal_data,
			]
		);

		return true;
	}

	/**
	 * @param \Illuminate\Http\Request $request
	 *
	 * @return \App\Models\Hotels\HotelUser
	 */
	public function searchUser(Request $request): HotelUser
	{
		$str = trim($request->term);

		return HotelUser::select('id', 'name', 'phone', 'email')
			->where('hotel_id', auth()->user()->hotel_id)
			->where(
				function ($query) use ($str) {
					$query->where('name', 'like', '%' . $str . '%')
						->orWhere('phone', 'like', '%' . $str . '%')
						->orWhere('email', 'like', '%' . $str . '%');
				}
			)
			->get();
	}

	/**
	 * @param int $id
	 *
	 * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
	 */
	public function destroy(int $id)
	{
		$user = User::whereId($id)->first();

		if ($this->checkUser($user) === true) {
			$user->delete();

			return redirect(route('hotel.crm-users.index'))->with('success', __('forms.deleted'));
		} else {
			return redirect(route('hotel.crm-users.index'))->with('status', __('forms.not-enough-permissions'));
		}
	}

	/**
	 * @param \App\Models\User $user
	 *
	 * @return bool
	 */
	private function checkUser(User $user): bool
	{
		if (
			$user->id === auth()->user()->id ||
			$user->hotel_id !== auth()->user()->hotel_id ||
			auth()->user()->hotel_main != true
		) {
			return false;
		} else {
			return true;
		}
	}
}

app/Http/Controllers/User/Profile/SettingsController.php
<?php

namespace App\Http\Controllers\User\Profile;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

/**
 * Class SettingsController
 *
 * @package App\Http\Controllers\User\Profile
 */
class SettingsController extends Controller
{
    /**
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        return view('user.profile.settings', ['item' => auth()->user()]);
    }

    /**
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request): RedirectResponse
    {
        $request->validate([
            'lang_id' => 'required',
            'name'    => 'required',
            'phone'    => 'required',
        ]);

        $item          = User::find(auth()->user()->id);
        $item->lang_id = $request->lang_id;
        $item->name    = $request->name;
        $item->phone   = $request->phone;

        $item->save();

        return back()->with('status', __('forms.edited'));
    }
}

app/Http/Controllers/User/UsersController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Interfaces\RoleCodes;
use App\Models\Permissions\CrmRole;
use App\Models\User;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

/**
 * Class UsersController
 *
 * @package App\Http\Controllers\User
 */
class UsersController extends Controller implements RoleCodes
{
	/**
	 * @var \App\Models\User
	 */
	private $user;

	/**
	 * UsersController constructor.
	 *
	 * @param \App\Models\User $user
	 */
	public function __construct(
		User $user
	) {
		$this->user = $user;
	}

	/**
	 * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
	 */
	public function index()
	{
		$this->items = User::hotelUsers()
			->paginate(setting('site.perpage'));

		return view(
			'hotel.users.items',
			[
				'items' => $this->items
			]
		);
	}

	/**
	 * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
	 */
	public function create()
	{
		return view(
			'hotel.users.ajax.addCrmUser',
			[
				'roles' => CrmRole::all(),
			]
		);
	}

	/**
	 * @param \Illuminate\Http\Request $request
	 *
	 * @return void
	 */
	public function store(Request $request)
	{
		$request->validate([
			'name'     => 'required',
			'phone'    => 'required',
			'email'    => 'required|unique:users',
			'lang_id'  => 'required',
			'role_id'  => 'required',
			'password' => 'required|min:8|confirmed',
		]);

		$request->name  = trim($request->name);
		$request->phone = str_replace(' ', '', $request->phone);
		$request->email = trim($request->email);

		User::create(
			[
				'lang_id'  => $request->lang_id,
				'role_id'  => $this->role('user')->id,
				'crm_role_id'  => $request->role_id,
				'hotel_id' => auth()->user()->hotel_id,
				'name'     => $request->name,
				'phone'    => $request->phone,
				'email'    => $request->email,
				'crm'      => true,
				'password' => Hash::make($request->password),
			]
		);
	}

	/**
	 * @param int $userId
	 *
	 * @return bool|\Illuminate\Http\RedirectResponse
	 */
	public function blocked(
		int $userId
	): RedirectResponse {
		$user        = $this->user->whereId($userId)->first();

		if ($user && $user->id !== auth()->user()->id) {
			$blockedTime = is_null($user->blocked_at) ? now() : null;

			$user->update(
				[
					'blocked_at' => $blockedTime,
				]
			);
		}

		return back();
	}
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

/**
 * Class UserController
 *
 * @package App\Http\Controllers
 */
class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        return view('user/profile');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function editProfile()
    {
        return view(
            'user.profile.edit',
            [
                'item' => auth()->user(),
            ]
        );
    }

    /**
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function updateProfile(Request $request): RedirectResponse
    {
        $request->validate([
            'lang_id' => 'required',
            'name'    => 'required',
            'email'   => 'required',
        ]);

        $item          = auth()->user();
        $item->lang_id = $request->lang_id;
        $item->name    = $request->name;
        $item->email   = $request->email;

        $item->save();

        return back()->with('status', __('forms.edited'));
    }
}

resources/views/hotel/users/ajax/addCrmUser.blade.php
<h3>{{ __('tables.user') }}: {{ __('titles.add') }}</h3>

<ul class="formErrors"></ul>

<form method="POST" action="{{ route('hotel.crm-users.store') }}" class="form-a ajax-send">
    @csrf
    <div class="row">
        <div class="form-group col-md-12">
            {!! Form::label('name', __('forms.name')) !!}
            {!! Form::text('name', null, ['class' => 'form-control', 'required' => true]) !!}
            @error('name')
            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
            @enderror
        </div>
        <div class="form-group col-md-12">
            {!! Form::label('phone', __('forms.phone')) !!}
            {!! Form::text('phone', null, ['class' => 'form-control', 'required' => true]) !!}
            @error('email')
            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
            @enderror
        </div>
        <div class="form-group col-md-12">
            {!! Form::label('email', __('forms.email')) !!}
            {!! Form::email('email', null, ['class' => 'form-control', 'required' => true]) !!}
            @error('email')
            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
            @enderror
        </div>
        <div class="form-group col-md-12">
            <label for="role_id">{{ __('settings.role') }}</label>
            <select
                class="form-control"
                name="role_id"
                required
                id="role_id">
                @foreach($roles as $k => $v)
                    <option
                        value="{{ $v->id }}">{{ $v->name }}</option>
                @endforeach
            </select>

            @error('role_id')
            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
            @enderror
        </div>
        <div class="form-group col-md-12">
            <label for="lang_id">{{ __('settings.language') }}</label>
            <select
                class="form-control"
                name="lang_id"
                required
                id="lang_id">
                @foreach(resolve(\App\Http\Controllers\Controller::class)->mainLanguages() as $k => $v)
                    <option
                        value="{{ $v->id }}"{{ app()->getLocale() == $v->const ? ' selected' : false }}>{{ $v->data->title }}</option>
                @endforeach
            </select>

            @error('lang_id')
            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
            @enderror
        </div>
        <div class="form-group col-md-12">
            {!! Form::label('password', __('forms.password')) !!}
            {!! Form::text('password', null, ['class' => 'form-control', 'required' => true]) !!}
            @error('password')
            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
            @enderror
        </div>
        <div class="form-group col-md-12">
            {!! Form::label('password_confirmation', __('forms.password_confirmation')) !!}
            {!! Form::text('password_confirmation', null, ['class' => 'form-control', 'required' => true]) !!}
            @error('password_confirmation')
            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
            @enderror
        </div>

        <div class="form-group col-md-4">
            {{ Form::submit(__('buttons.add'), ['class' => 'btn btn-primary']) }}
        </div>
    </div>
</form>

resources/views/hotel/users/ajax/addUser.blade.php
<h3>{{ __('tables.user') }}: {{ __('titles.add') }}</h3>

<ul class="formErrors"></ul>

<form method="POST" action="{{ route('hotel.users.store') }}" class="form-a ajax-send">
    @csrf
    <div class="row">
        <div class="form-group col-md-12">
            {!! Form::label('name', __('forms.name')) !!}
            {!! Form::text('name', null, ['class' => 'form-control', 'required' => true]) !!}
            @error('name')
            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
            @enderror
        </div>
        <div class="form-group col-md-12">
            {!! Form::label('phone', __('forms.phone')) !!}
            {!! Form::text('phone', null, ['class' => 'form-control', 'required' => true]) !!}
            @error('email')
            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
            @enderror
        </div>
        <div class="form-group col-md-12">
            {!! Form::label('email', __('forms.email')) !!}
            {!! Form::email('email', null, ['class' => 'form-control']) !!}
            @error('email')
            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
            @enderror
        </div>
        <div class="form-group col-md-12">
            <label for="lang_id">{{ __('settings.language') }}</label>
            <select
                class="form-control"
                name="lang_id"
                required
                id="lang_id">
                @foreach(resolve(\App\Http\Controllers\Controller::class)->mainLanguages() as $k => $v)
                    <option
                        value="{{ $v->id }}"{{ app()->getLocale() == $v->const ? ' selected' : false }}>{{ $v->data->title }}</option>
                @endforeach
            </select>

            @error('lang_id')
            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
            @enderror
        </div>
        <div class="form-group col-md-12">
            {!! Form::label('personalData', __('forms.personal-data')) !!}
            {!! Form::textarea('personalData', null, ['class' => 'form-control']) !!}
            @error('email')
            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
            @enderror
        </div>

        <div class="form-group col-md-4">
            {{ Form::submit(__('buttons.add'), ['class' => 'btn btn-primary']) }}
        </div>
    </div>
</form>