routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});

// Requests
Route::group(
    ['middleware' => 'hotel.admin'],
    function () {

        // Main
        Route::get('/', 'MainController@index')->name('main');

        // Orders
        Route::resources(['orders' => 'Hotel\OrdersController'], ['as' => 'hotel']);
        Route::get('/orders/restore/{id}', 'Hotel\OrdersController@restore')->name('hotel.orders.restore');

        // Rooms
        Route::resources(['rooms' => 'Hotel\RoomsController'], ['as' => 'hotel']);
        Route::get('/rooms/restore/{id}', 'Hotel\RoomsController@restore')->name('hotel.rooms.restore');

        // Users
        Route::resources(['users' => 'Hotel\UsersController'], ['as' => 'hotel']);
        Route::get('/search-user', 'Hotel\UsersController@searchUser')->name('hotel.users.searchUser');

        // Guests
        Route::resources(['guests' => 'Hotel\GuestsController'], ['as' => 'hotel']);
        Route::get('/guests/restore/{id}', 'Hotel\GuestsController@restore')->name('hotel.guests.restore');

        // Services
        Route::resources(['services' => 'Hotel\ServicesController'], ['as' => 'hotel']);
        Route::post('/services/update/{id}', 'Hotel\ServicesController@update')->name('hotel.services.update');
        Route::get('/services/restore/{id}', 'Hotel\ServicesController@restore')->name('hotel.services.restore');
        Route::post('/services/image-uploader', 'Hotel\ServicesController@imageUploader')
            ->name('hotel.services.imageUploader');
        Route::post('/services/image-delete', 'Hotel\ServicesController@destroyImage')
            ->name('hotel.services.destroyImage');
        Route::get('/services/archive/{id}/{value}', 'Hotel\ServicesController@archive')
            ->name('hotel.services.archive');

        // Offers
        Route::resources(['offers' => 'Hotel\OffersController'], ['as' => 'hotel']);
        Route::post('/offers/update/{id}', 'Hotel\OffersController@update')->name('hotel.offers.update');
        Route::get('/offers/archive/{id}/{value}', 'Hotel\OffersController@archive')->name('hotel.offers.archive');
        Route::post('/offers/uploader/image-uploader', 'Hotel\OffersController@imageUploader')
            ->name('hotel.offers.imageUploader');
        Route::post('/offers/uploader/image-delete', 'Hotel\OffersController@destroyImage')
            ->name('hotel.offers.destroyImage');

        // News
        Route::resources(['news' => 'Hotel\NewsController'], ['as' => 'hotel']);
        Route::get('/news/archive/{id}/{value}', 'Hotel\NewsController@archive')->name('hotel.news.archive');

        // Articles
        Route::resources(['articles' => 'Hotel\ArticlesController'], ['as' => 'hotel']);
        Route::get('/articles/archive/{id}/{value}', 'Hotel\ArticlesController@archive')
            ->name('hotel.articles.archive');
        Route::get('/hotel/contacts', 'Hotel\ArticlesController@contacts')->name('hotel.contacts');
        Route::patch('/hotel/contacts', 'Hotel\ArticlesController@contactsUpdate')->name('hotel.contacts.update');

        // Settings
        Route::group(['prefix' => 'settings'], function () {
            Route::get('/', 'Hotel\SettingsController@index')->name('hotel.settings.index');
            Route::put('/', 'Hotel\SettingsController@update')->name('hotel.settings.update');
            Route::get('/languages', 'Hotel\SettingsController@languages')->name('hotel.settings.languages');
            Route::get('/currencies', 'Hotel\SettingsController@currencies')->name('hotel.settings.currencies');
        });

        Route::get('/translation', 'MainController@translation')->name('translation');

        // Profile
        Route::group(['prefix' => 'profile'], function () {
            Route::get('/settings', 'User\Profile\SettingsController@index')->name('profile.settings');
            Route::patch('/settings', 'User\Profile\SettingsController@update')->name('profile.settings.update');
        });

        // Users
        Route::resources(['crm-users' => 'User\UsersController'], ['as' => 'hotel']);
		Route::get('/crm-users/block/{id}', 'User\UsersController@blocked')
			->name('hotel.users.block');
    }
);

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

app/Models/Hotels/Hotel.php
<?php

namespace App\Models\Hotels;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

/**
 * @method static create()
 * @method static whereId($hotel_id)
 * @method static find($hotel_id)
 */
class Hotel extends Model
{
    /**
     * @param int|null $langId
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function data(int $langId = null): BelongsTo
    {
        $langId = $langId ?? auth()->user()->lang_id;

        return $this->belongsTo('App\Models\Hotels\HotelData', 'id', 'hotel_id')
            ->where(['lang_id' => $langId]);
    }

    /**
     * Guests
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function guests(): BelongsTo
    {
        return $this->belongsTo('App\Models\User', 'id', 'hotel_id');
    }

    /**
     * Languages
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function languages(): BelongsToMany
    {
        return $this->belongsToMany(
            'App\Models\Language',
            config('database.connections.mysql.database') . '.hotel_languages',
            'hotel_id',
            'lang_id'
        )
            ->orderBy('order');
    }

    /**
     * Currency
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function currencies(): BelongsToMany
    {
        return $this->belongsToMany(
            'App\Models\Currency',
            config('database.connections.mysql.database') . '.hotel_currencies',
            'hotel_id'
        )
            ->orderBy('order');
    }
}

app/Models/Hotels/HotelCurrency.php
<?php

namespace App\Models\Hotels;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * Class HotelCurrency
 *
 * @package App\Models\Hotels
 * @method static create(array $array)
 * @method static where(array $array)
 */
class HotelCurrency extends Model
{
    /**
     * @var bool
     */
    public $timestamps = false;

    /**
     * @var string[]
     */
    protected $fillable = [
        'hotel_id',
        'currency_id',
    ];

    /**
     * Currency
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     * @author ansotov
     */
    public function currency(): BelongsTo
    {
        return $this->belongsTo('App\Models\Currency', 'id', 'currency_id');
    }
}

app/Models/Hotels/HotelData.php
<?php

namespace App\Models\Hotels;

use Illuminate\Database\Eloquent\Model;

/**
 * Class HotelData
 *
 * @package App\Models\Hotels
 * @method static create(array $array)
 * @method static where(array $array)
 */
class HotelData extends Model
{
    /**
     * @var bool
     */
    public $timestamps = false;

    /**
     * @var string[]
     */
    protected $fillable = [
        'lang_id',
        'hotel_id',
        'title',
        'description',
    ];
}

app/Models/Hotels/HotelGuestCode.php
<?php

namespace App\Models\Hotels;

use Illuminate\Database\Eloquent\Model;

/**
 * Class HotelGuestCode
 *
 * @package App\Models\Hotels
 * @method static where(array $array)
 */
class HotelGuestCode extends Model
{
    /**
     * @var string[]
     */
    protected $fillable = [
        'guest_id',
        'code',
    ];
}

app/Models/Hotels/HotelOrderStatusData.php
<?php

namespace App\Models\Hotels;

use Illuminate\Database\Eloquent\Model;

/**
 * Class HotelOrderStatusData
 *
 * @package App\Models\Hotels
 */
class HotelOrderStatusData extends Model
{
    //
}

app/Models/Hotels/HotelServiceImage.php
<?php

namespace App\Models\Hotels;

use Illuminate\Database\Eloquent\Model;

/**
 * Class HotelServiceImage
 *
 * @package App\Models\Hotels
 * @method static where(array $array)
 */
class HotelServiceImage extends Model
{
    //
}

app/Http/Controllers/Hotel/ArticlesController.php
<?php

namespace App\Http\Controllers\Hotel;

use App\Http\Controllers\Controller;
use App\Jobs\Hotels\ArticleDataTranslate;
use App\Jobs\Hotels\ContactArticleDataTranslate;
use App\Models\Articles\Article;
use App\Models\Articles\ArticleData;
use App\Models\Articles\ContactArticle;
use App\Models\Articles\ContactArticleData;
use Exception;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

/**
 * Class ArticlesController
 *
 * @package App\Http\Controllers\Hotel
 */
class ArticlesController extends Controller
{
    use SoftDeletes;

    /**
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Request $request)
    {
        if ($request->archive) {
            $this->items = Article::archive()->paginate(setting('site.perpage'));
        } else {
            $this->items = Article::hotelArticles()->paginate(setting('site.perpage'));
        }

        return view('hotel.articles.items', ['items' => $this->items]);
    }

    /**
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('hotel.articles.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required|array',
        ]);

        $request->request->add(['slug' => Str::slug($request->title[auth()->user()->language->id] . '-' . time())]);

        $request->validate([
            'slug' => 'required|unique:articles,slug,hotel_id',
        ]);

        $item = new Article(
            [
                'hotel_id'     => auth()->user()->hotel_id,
                'slug'         => $request->slug,
                'published_at' => $request['published_at'],
                'active'       => isset($request['active']) ? 1 : 0,
            ]
        );
        $item->save();

        foreach ($this->hotelLanguages(auth()->user()->hotel_id) as $v) {
            $subItem = new ArticleData(
                [
                    'lang_id'     => $v->lang_id,
                    'article_id'  => $item->id,
                    'title'       => $request->title[$v->lang_id],
                    'description' => $request->description[$v->lang_id],
                    'text'        => $request->text[$v->lang_id],
                ]
            );
            $subItem->save();
        }

        // Queue translations
        ArticleDataTranslate::dispatch($item, $request->all(), auth()->user()->language, auth()->user());

        return redirect(route('hotel.articles.index'))->with('status', __('forms.saved'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(int $id)
    {
        return view('hotel.articles.edit', [
            'item' => Article::find($id),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int                      $id
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(Request $request, int $id)
    {
        $request->validate([
            'title' => 'required',
        ]);

        $item = Article::whereId($id)->first();
        $item->update(
            [
                'published_at' => $request['published_at'],
                'active'       => isset($request['active']) ? 1 : 0,
            ]
        );

        // Delete conditions
        ArticleData::where(['article_id' => $id])->delete();

        foreach ($this->hotelLanguages(auth()->user()->hotel_id) as $v) {
            $subItem = new ArticleData(
                [
                    'lang_id'     => $v->lang_id,
                    'article_id'  => $id,
                    'title'       => $request->title[$v->lang_id],
                    'description' => $request->description[$v->lang_id],
                    'text'        => $request->text[$v->lang_id],
                ]
            );
            $subItem->save();
        }

        // Queue translations
        ArticleDataTranslate::dispatch($item, $request->all(), auth()->user()->language, auth()->user());

        return redirect(route('hotel.articles.index'))->with('status', __('forms.edited'));
    }

    /**
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function contacts()
    {
        $this->item = ContactArticle::where(function ($query) {
            $query->hotelItem();
        })->first();

        return view('hotel.settings.contacts', [
            'item' => $this->item,
        ]);
    }

    /**
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function contactsUpdate(
        Request $request
    ) {
        $this->item = ContactArticle::hotelItem()->first();

        if ($this->item) {
            // Delete conditions
            ContactArticleData::where(['article_id' => $this->item->id])->delete();

            foreach ($request->text as $k => $v) {
                try {
                    $item = new ContactArticleData(
                        [
                            'lang_id'    => $k,
                            'article_id' => $this->item->id,
                            'text'       => $v,
                        ]
                    );
                    $item->save();
                } catch (Exception $exception) {
                    echo $k . '----';
                    dd($exception->getMessage());
                }
            }

            // Queue translations
            ContactArticleDataTranslate::dispatch(
                $this->item,
                $request->all(),
                auth()->user()->language,
                auth()->user()
            );
        }

        return redirect(route('hotel.contacts'))->with('status', __('forms.edited'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function destroy(int $id)
    {
        Article::where(['id' => $id])->delete();

        return redirect(route('hotel.articles.index'))->with('status', __('forms.deleted'));
    }

    /**
     * @param $id
     * @param $value
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function archive($id, $value)
    {
        Article::where(['id' => $id])->update(
            [
                'archive' => $value,
            ]
        );

        $status = $value == true ? __('forms.in-archive') : __('forms.restored');

        return redirect(route('hotel.articles.index'))->with('status', $status);
    }
}

app/Http/Controllers/Hotel/OrdersController.php
<?php

namespace App\Http\Controllers\Hotel;

use App\Http\Controllers\Controller;
use App\Models\Orders\Order;
use App\Models\Orders\OrderStatus;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

/**
 * Class OrdersController
 *
 * @package App\Http\Controllers\Hotel
 */
class OrdersController extends Controller
{
	/**
	 * @param \Illuminate\Http\Request $request
	 *
	 * @return \Illuminate\Contracts\View\View
	 */
	public function index(Request $request): View
	{
		$this->items = Order::filter($request->all())
			->where(function ($query) {
				$query->hotelOrders();
			})
			->paginate(setting('site.perpage'));

		return view(
			'hotel.orders.items',
			[
				'items'    => $this->items,
				'statuses' => OrderStatus::all(),
			]
		);
	}

	/**
	 * @param $id
	 *
	 * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
	 */
	public function show($id)
	{
		return view(
			'hotel.orders.show',
			[
				'item'     => Order::whereId($id)->first(),
				'statuses' => OrderStatus::all(),
			]
		);
	}

	/**
	 * @param \Illuminate\Http\Request $request
	 * @param                          $id
	 *
	 * @return \Illuminate\Http\RedirectResponse
	 */
	public function update(Request $request, $id): RedirectResponse
	{
		$request->validate([
			'status_id' => 'required',
		]);

		$item            = Order::find($id);
		$item->status_id = $request['status_id'];

		$item->save();

		return back()->with('status', __('forms.updated'));
	}
}

resources/views/hotel/guests/create.blade.php
@extends('layouts.app')

@section('title')
    {{ __('titles.guests') }}: {{ __('titles.add') }}
@endsection

@section('content')
    <div class="col-md-12 col-sm-12  ">
        <div class="x_panel">
            <div class="x_content">

                {!! Form::open(['method' => 'post', 'url' => route('hotel.guests.store')]) !!}

                <div class="form-group col-md-4">
                    {!! Form::label('room_id', __('tables.number')) !!}
                    <select name="room_id" class="form-control">
                        @foreach($rooms as $k => $v)
                            <option
                                value="{{ $v->id }}">{{ $v->number }}</option>
                        @endforeach
                    </select>
                </div>

                <div class="form-group col-md-4">
                    {!! Form::label('user_id', __('tables.user')) !!}
                    {{--<select name="user_id" class="form-control sumoselect">
                        @foreach($users as $k => $v)
                            <option value="{{ $v->id }}">{{ $v->name }}</option>
                        @endforeach
                    </select>--}}

                    {!! Form::text('', null, ['id' => 'searchUser', 'class' => 'form-control', 'required' => true]) !!}
                    {!! Form::hidden('user_id', null, ['id' => 'searchUser', 'class' => 'form-control', 'required' => true]) !!}
                </div>

                <div class="form-group col-md-4">
                    {!! Form::label('user_id', __('tables.new-user-description')) !!}

                    <div class="clearfix"></div>
                    <a
                        href="javascript:void(0);" class="btn btn-primary popup-ajax-link"
                        data-url="{{ route('hotel.users.create') }}">{{ __('buttons.new-user') }}</a>
                </div>

                <div class="clearfix"></div>

                <div class="form-group col-md-4">
                    {!! Form::label('start_at', __('tables.start_at')) !!}
                    {!! Form::date('start_at', null, ['class' => 'form-control', 'required' => true]) !!}
                </div>

                <div class="form-group col-md-4">
                    {!! Form::label('end_at', __('tables.end_at')) !!}
                    {!! Form::date('end_at', null, ['class' => 'form-control', 'required' => true]) !!}
                </div>

                <div class="form-group col-md-12">
                    {!! Form::label('comment', __('tables.comment')) !!}
                    {!! Form::textarea('comment', null, ['class' => 'form-control ckeditor']) !!}
                </div>

                <div class="form-group col-md-4">
                    {{ Form::submit(__('buttons.save'), ['class' => 'btn btn-primary']) }}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/hotel/guests/edit.blade.php
@extends('layouts.app')

@section('title')
    {{ __('titles.guests') }}: {{ __('titles.edit') }}
@endsection

@section('content')
    <div class="col-md-12 col-sm-12  ">
        <div class="x_panel">
            <div class="x_content">

                {!! Form::open(['method' => 'post', 'url' => route('hotel.guests.update', $item->id)]) !!}
                @method('PATCH')

                <div class="form-group col-md-4">
                    <div>
                        {!! Form::label('room_id', __('tables.number')) !!}
                        <div class="input-group">
                            {!! Form::text('room_id', $item->room->number, ['class' => 'form-control', 'disabled' => 'disabled']) !!}
                            <a href="" class="btn btn-info">
                                <i class="fa fa-key"></i>
                            </a>
                        </div>
                    </div>

                    <div class="clearfix"></div>

                    <div>
                        {!! Form::label('user_id', __('tables.guest')) !!}
                        <div class="input-group">
                            {!! Form::text('user_id', $item->user->name, ['class' => 'form-control', 'disabled' => 'disabled']) !!}
                            <a href="" class="btn btn-info">
                                <i class="fa fa-user"></i>
                            </a>
                        </div>
                    </div>

                    <div class="clearfix"></div>

                    <div class="form-group col-md-6" style="padding-left: 0">
                        {!! Form::label('start_at', __('tables.start_at')) !!}
                        {!! Form::date('start_at', $item->start_at, ['class' => 'form-control']) !!}
                    </div>

                    <div class="form-group col-md-6" style="padding: 0 4px 0 0">
                        {!! Form::label('end_at', __('tables.end_at')) !!}
                        {!! Form::date('end_at', $item->end_at, ['class' => 'form-control']) !!}
                    </div>
                </div>

                <div class="form-group col-md-8">

                    {{--<div class="form-group col-md-12">
                        {!! Form::label('room_id', __('tables.booked_dates')) !!}
                        <div class="input-group">
                            --}}{{--<div id='calendar'></div>--}}{{--
                        </div>
                    </div>--}}
                </div>


                    <div class="form-group col-md-12">
                        {!! Form::label('comment', __('tables.comment')) !!}
                        {!! Form::textarea('comment', $item->comment, ['class' => 'form-control ckeditor']) !!}
                    </div>

                    <div class="form-group col-md-4">
                        {{ Form::submit(__('buttons.save'), ['class' => 'btn btn-primary']) }}
                    </div>

            </div>
        </div>
    </div>
@endsection

{{--@section('footer_scripts')
    <link href="{{ asset('vendors/fullcalendar/dist/fullcalendar.min.css') }}" rel="stylesheet">
    <script src="{{ asset('vendors/moment/min/moment.min.js') }}"></script>
    <script src="{{ asset('vendors/fullcalendar/dist/fullcalendar.min.js') }}"></script>
@endsection--}}

resources/views/hotel/guests/items.blade.php
@extends('layouts.app')

@section('title')
    {{ __('titles.guests') }}
@endsection

@section('content')
    <div class="col-md-12 col-sm-12  ">
        <div class="x_panel">
            <div class="x_content">
                <div class="filters">
                    <ul class="list-inline float-right">
                        <li class="list-inline-item">
                            <a
                                href="{{ route('hotel.guests.create') }}" class="btn btn-outline-primary btn-sm"
                                role="button"
                                aria-pressed="true">{{ __('buttons.add') }}</a>
                        </li>
                    </ul>
                    {{--<div class="form-group col-md-4">
                        <select class="form-control" onchange="if (this.value) window.location.href=this.value">
                            <option value="{{ route('hotel.guests.index') }}">{{ __('forms.actives') }}</option>
                            <option
                                value="{{ route('hotel.guests.index', ['trashed' => true]) }}"{{ request('trashed') ? ' selected' : false }}>{{ __('forms.with-trashed') }}</option>
                            <option
                                value="{{ route('hotel.guests.index', ['onlyTrashed' => true]) }}"{{ request('onlyTrashed') ? ' selected' : false }}>{{ __('forms.only-trashed') }}</option>
                        </select>
                    </div>--}}
                </div>

                <table class="table table-striped table-hover table-bordered">
                    <thead>
                    <tr>
                        <th scope="col" width="20">{{ __('tables.number') }}</th>
                        <th scope="col" width="250">{{ __('tables.name') }}</th>
                        <th scope="col" width="120">{{ __('tables.start_at') }}</th>
                        <th scope="col" width="120">{{ __('tables.end_at') }}</th>
                        <th scope="col" width="150" style="background-color: #fddbdb">{{ __('tables.code') }}</th>
                        <th scope="col" width="">{{ __('tables.comment') }}</th>
                        <th scope="col" width="120"></th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($items as $k => $v)
                        <tr{{ $v->trashed() ? ' class=table-danger' : false }}>
                            <th scope="row">{{ $v->room->number }}</th>
                            <td>{{ $v->user->name }}</td>
                            <td>{{ $v->start_at->format('d.m.Y') }}</td>
                            <td>{{ $v->end_at->format('d.m.Y') }}</td>
                            <td style="background-color: #fddbdb"><b>{{ $v->code ? $v->code->code : false }}</b></td>
                            <td>{!! $v->user->comment !!}</td>
                            <td>
                                <a
                                    href="{{ route('hotel.guests.edit', $v) }}"
                                    class="btn btn-outline-primary btn-sm" role="button"
                                    aria-pressed="true"
                                    title="{{ __('buttons.edit') }}">
                                    <i class="fas fa-edit"></i>
                                </a>
                                @if($v->trashed())
                                    <a
                                        href="{{ route('hotel.guests.restore', ['id' => $v->id, 'params' => request()]) }}"
                                        class="btn btn-outline-primary btn-sm" role="button"
                                        aria-pressed="true"
                                        onclick="return confirm('{{ __('messages.are-you-sure') }}')"
                                        title="{{ __('buttons.restore') }}">
                                        <i class="fas fa-trash-restore"></i>
                                    </a>
                                @else
                                    {!! Form::open(['method' => 'DELETE','route' => ['hotel.guests.destroy', $v->id],'style'=>'display:inline']) !!}
                                    {!! Form::button('<i class="fas fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-sm', 'onclick' => 'return confirm("' . __('messages.are-you-sure') . '")']) !!}
                                    {!! Form::close() !!}
                                @endif
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                {{ $items->links() }}
            </div>
        </div>
    </div>
@endsection